repository:
  name: lab-asg-2025smr
  description: 2025å¹´å¤èª²é¡Œ
  private: true
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: develop
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: false
  enable_vulnerability_alerts: false
labels:
  - name: âœ¨æ©Ÿèƒ½è¿½åŠ 
    color: A2EEEF
    description: æ–°ã—ã„æ©Ÿèƒ½ã®è¦æœ›
  - name: ğŸ†™ä¾å­˜é–¢ä¿‚
    color: 0366D6
    description: ä¾å­˜é–¢ä¿‚ã‚’æ›´æ–°ã™ã‚‹Pull Request
  - name: ğŸ›ãƒã‚°
    color: D73A4A
    description: æ„å›³ã—ãªã„å‹•ä½œ
  - name: ğŸ‘¯é‡è¤‡
    color: CFD3D7
    description: ä¼¼ãŸIssueã‚„Pull RequestãŒã‚ã‚‹
  - name: ğŸ‘·CI/CD
    color: 008672
    description: GitHub Actionsãªã©ã®CI/CDã«é–¢é€£
  - name: ğŸ’¬è³ªå•
    color: D876E3
    description: ãƒ—ãƒ­ã‚°ãƒ©ãƒ ã‚„ç’°å¢ƒæ§‹ç¯‰ã«é–¢ã™ã‚‹è³ªå•
  - name: ğŸ’»ãƒ•ãƒ­ãƒ³ãƒˆã‚¨ãƒ³ãƒ‰
    color: F7DF1E
    description: JavaScriptã‚„CSSãªã©ã®ãƒ•ãƒ­ãƒ³ãƒˆã‚¨ãƒ³ãƒ‰ã«é–¢é€£
  - name: ğŸ“æ–‡æ›¸
    color: 0075CA
    description: æ–‡æ›¸ã«æ”¹å–„ã‚„è¿½åŠ ãŒå¿…è¦
  - name: ğŸ«€ãƒãƒƒã‚¯ã‚¨ãƒ³ãƒ‰
    color: 4F5B93
    description: PHPãªã©ã®ãƒãƒƒã‚¯ã‚¨ãƒ³ãƒ‰ã«é–¢é€£
milestones:
  - title: milestone-title
    description: milestone-description
    state: open
branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      enforce_admins: true
      required_linear_history: false
      restrictions: null
  - name: develop
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      enforce_admins: true
      required_linear_history: false
      restrictions: null